stages:
  - build

build-job:
  stage: build
  tags:
    - my_runner
  script:
    - cd src/cat && make s21_cat
    - cd ../grep && make s21_grep
  artifacts:
    paths:
      - src/cat/
      - src/grep/
    expire_in: 30 days
  only:
    - develop
