stages:
  - style
  - build

style-job:
  stage: style
  tags: 
    - style
  script:
    - clang-format -Werror -n src/cat/cat.c src/grep/grep.c
  only:
    - develop  

build-job:
  stage: build
  tags:
    - build
  script:
    - cd src/cat && make s21_cat
    - cd ../grep && make s21_grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days
  only:
    - develop
                   
