stages:
  - style
  - build
  - test
  - deploy

.notify: &notify
  - |
    source /home/edward828/config.conf
    MESSAGE=$(if [[ "$CI_JOB_STATUS" =~ "failed" ]]; then echo "$CI_JOB_STAGE stage: FAIL"; else echo "$CI_JOB_STAGE stage: SUCCESS"; fi)
    ssh "$REMOTE_USER"@"$REMOTE_SERVER" "curl -s -X POST $API_URL -d chat_id=$CHAT_ID -d text=\"$MESSAGE\"" > "/dev/null"

style-job:
  stage: style
  tags: 
    - style
  script:
    - clang-format -Werror -n src/cat/cat.c src/grep/grep.c
  after_script:
    - *notify
  only:
    - develop  

build-job:
  stage: build
  tags:
    - build
  script:
    - cd src/cat && make s21_cat
    - cd ../grep && make s21_grep
  after_script:
    - *notify
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days
  only:
    - develop
        
test-job:
  stage: test
  tags:
    - test
  script:
    - cd src/cat/
    - ./script.sh
    - cd ../grep/
    - make tests
  after_script:
    - *notify
  only:
    - develop

deploy-job:
  stage: deploy
  tags: 
    - deploy
  when: manual
  script:
    - |
      if scp ./src/cat/s21_cat ./src/grep/s21_grep rrasta@192.168.56.102:~/ ; then
        ssh rrasta@192.168.56.102 "sudo mv s21_cat s21_grep /usr/local/bin"
        echo -e "\e[32mSuccesfully copy artifacts to /usr/local/bin\e[0m"
      else
        echo -e "\e[31mCAN'T COPY ARTIFACTS\e[0m"
        exit 1
      fi
  after_script:
    - *notify 
  only:
    - develop      

